AddonId: SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_2.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_4.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.1.0
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_5.pext
    Changelog:
    - Updated localizations
    - Fix not launching Steam with the configured actions when game is starting
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_8.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 2.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_9.pext
    Changelog:
    - Updated localizations
  - Version: 2.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_10.pext
    Changelog:
    - Updated localizations
  - Version: 2.11
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_11.pext
    Changelog:
    - Updated localizations
  - Version: 2.12
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_12.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 2.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_13.pext
    Changelog:
    - 'Fix adding incorrect feature from menu function'
  - Version: 2.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_14.pext
    Changelog:
    - 'Fix inclusion feature not correctly working in Selective Mode'
  - Version: 2.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_15.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_16.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.30_901ef791/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_17.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_01d659e6/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_18.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.19
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_9bdaf3ae/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_19.pext
    Changelog:
    - 'Updated localizations'