AddonId: GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_0.pext
    Changelog:
    - Updated localizations
  - Version: 1.1
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_1.pext
    Changelog:
    - Updated localizations
  - Version: 1.2
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_2.pext
    Changelog:
    - Updated localizations
  - Version: 1.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_3.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 1.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_4.pext
    Changelog:
    - Updated localizations
  - Version: 1.5
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_5.pext
    Changelog:
    - Updated localizations
  - Version: 1.6
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_6.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 1.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.16_af6a49cc/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_7.pext
    Changelog:
    - 'Added option to automatically calculate the game size after it is stopped (Enabled by default)'
  - Version: 1.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_8.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.20_b118c6cd/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_9.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.23_32f4ed05/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_10.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.11
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_11.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.12
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_01d659e6/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_12.pext
    Changelog:
    - 'Updated localizations'
    - 'Added option to automatically calculate size of newly added games on library update'
    - 'Added option to automatically calculate size of that have been detected as modified since previous detection on library update'
  - Version: 1.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_ddc118cd/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_13.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.03_3ad2d023/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_14.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.07_98fa5f6c/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_15.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_9bdaf3ae/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_16.pext
    Changelog:
    - 'Updated localizations'